# Generated by Django 4.1.4 on 2022-12-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=1024, verbose_name='Nombre completo')),
                ('code', models.CharField(max_length=20, verbose_name='Cedula')),
                ('email', models.EmailField(max_length=254)),
                ('activated', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
